services:
  backend:
    build: .
    container_name: finance-app-backend
    environment:
      DATABASE_URL: file:./dev.db
      PORT: 3000
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules 